[package]
name = "doer"
version = "2.0.0-alpha.0"
edition = "2021"
authors = ["Nathan Samra <me@nathansamra.com>"]
description = "Doer is a tool designed to help you organise your day to day"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }
