[package]
name = "doer"
version = "2.0.0-alpha.0"
edition = "2021"
authors = ["Nathan Samra <me@nathansamra.com>"]
description = "Doer is a tool designed to help you organise your day to day"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive"] }
dirs = "5.0.0"
serde = { version = "1.0.160", features = ["derive"] }
tempfile = "3.5.0"
toml = "0.7.3"
